name: 'update-terraform-lockfile'
inputs:
  token:
    description: 'GitHub Token or PAT'
    required: true
    default: ''
  target-branch:
    description: 'Target branch for pull request'
    required: false
    default: 'main'
  pull-request-branch:
    description: 'Branch to push changes'
    required: false
    default: 'update-terraform-lockfile'
  user:
    description: 'Git username'
    required: false
    default: 'update-terraform-lockfile'
  email:
    description: 'Git email'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  commit-message:
    description: 'Commit message to use'
    required: false
    default: 'Updated terraform lockfile'
  working-directory:
    description: 'Directory to run the action from'
    required: false
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
    - run: |
        cd ${GITHUB_ACTION_PATH} && go build
        cd ${GITHUB_WORKSPACE}
        ${GITHUB_ACTION_PATH}/update-terraform-lockfile
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TARGET_BRANCH: ${{ inputs.target-branch }}
        INPUT_PULL_REQUEST_BRANCH: ${{ inputs.pull-request-branch }}
        INPUT_USER: ${{ inputs.user }}
        INPUT_EMAIL: ${{ inputs.email }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
